# Generated by Django 5.2.3 on 2025-11-17 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('JEFE', 'Jefe de Operadores'), ('OPERADOR', 'Operador Técnico'), ('PRODUCTOR', 'Productor')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('operadores', models.ManyToManyField(blank=True, related_name='programas_como_operador', to=settings.AUTH_USER_MODEL)),
                ('productores', models.ManyToManyField(blank=True, related_name='programas_como_productor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('archivo', models.FileField(upload_to='fx/')),
                ('scope', models.CharField(choices=[('INSTITUCIONAL', 'Institucional (público, editable solo por Jefe)'), ('PROGRAMA', 'De programa'), ('OPERADOR', 'Propio del operador')], default='PROGRAMA', max_length=20)),
                ('volumen_default', models.FloatField(default=1.0)),
                ('color_boton', models.CharField(blank=True, max_length=20)),
                ('tecla_rapida', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.categoriafx')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fx_propios', to=settings.AUTH_USER_MODEL)),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fx_programa', to='App.programa')),
            ],
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
